# Generated by Django 4.1.4 on 2022-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='films',
            field=models.IntegerField(default=0),
        ),
    ]
