# Generated by Django 4.1.4 on 2022-12-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_hoursresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursresult',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
