# Generated by Django 4.1.4 on 2022-12-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_hoursresult_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursresult',
            name='films',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hoursresult',
            name='publications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hoursresult',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
