# Generated by Django 4.1.4 on 2022-12-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_hoursresult_films_hoursresult_publications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
                ('publications', models.IntegerField(default=0)),
                ('films', models.IntegerField(default=0)),
            ],
        ),
    ]
