# Generated by Django 4.1.4 on 2023-01-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_eventshistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventshistory',
            name='month',
        ),
    ]
