# Generated by Django 4.1.4 on 2022-12-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='months',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.event'),
        ),
    ]
