# Generated by Django 4.1.4 on 2022-12-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_months_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='months',
            name='event',
        ),
        migrations.AddField(
            model_name='months',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
