# Generated by Django 4.1.4 on 2022-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_months_event_months_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='months',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
