# Generated by Django 4.1.4 on 2022-12-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_months_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='months',
            name='month',
        ),
    ]
