# Generated by Django 4.1.4 on 2022-12-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_months_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursresult',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
